language: node_js
node_js:
  - '7.6'
  - '8.6'
services:
  - docker
  - mongodb
sudo: required
before_install:
  - ".travis/setup.sh"
after_success:
  - npm run coverage
  - ".travis/build_docker.sh"
deploy:
  - provider: script
    script: ".travis/deploy.sh test"
    on:
      branch: ohm-505-setup-continuous-deployment
# depoy:
#   provider: script
#   script: ".travis/deploy.sh" staging
#   on:
#     branch: staging
